server:
  port: 8081

## DB Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/item-service?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Kiev
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: UTC
  jackson:
    time-zone: UTC
